### PR TITLE
add support for notification channels

### LINKED ISSUE #30: [FEATURE] Support notifications
### Is your feature request related to a problem?

Opensearch destinations seem to be deprecated with 2.0 and have been superseded by notifications, see https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/#questions-about-destinations and https://docs.aws.amazon.com/opensearch-service/latest/developerguide/alerting.html#alerting-notifications.

Using a `opensearch_destination` ressource with this provider and a Opensearch domain 2.x fails with

```
│ Error: elastic: Error 405 (Method Not Allowed)
```

### What solution would you like?

Support the notifications API in this provider: https://opensearch.org/docs/latest/observing-your-data/notifications/api/

### What alternatives have you considered?

Create notifications using direct API calls or using the Dashboards UI.

### Do you have any additional context?

no

### PR DESCRIPTION
**Pull request by alexconlin**
Signed-off-by: Alex Conlin-Oakley <458604+alexconlin@users.noreply.github.com>

### Description
Adds support for configuring channels in the OpenSearch notifications plugin.

### Issues Resolved
Closes #30

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Thanks for the contribution @alexconlin, I will take a look at this PR and provide feedback shortly.
Adding @bbarani @phillbaker @peterzhuamazon

**Comment by prudhvigodithi** [comment]
The test initially failed with error
```
  Running [/home/runner/golangci-lint-1.29.0-linux-amd64/golangci-lint run --out-format=github-actions --verbose --timeout=10m] in [] ...
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  Error: File is not `gofmt`-ed with `-s` (gofmt)
 ```
@alexconlin  can you run `golangci-lint run --out-format=github-actions ` on your local to replicate the error?
Thank you

**Comment by prudhvigodithi** [comment]
Thanks @alexconlin can you also run the https://github.com/hashicorp/terraform-plugin-docs, this should generate the resources and examples for this new notification support.

**Comment by prudhvigodithi** [comment]
LGTM, @alexconlin can you please generate the tfdocs?
@phillbaker please take a look when you get a chance. Thank you

**Comment by alexconlin** [comment]
@prudhvigodithi I have updated the documentation with tfplugindocs.

I notice that the `url` parameter has moved from Required to Optional. It does that when I generate docs on the main branch as well. It seems to be related to [this issue](https://github.com/hashicorp/terraform-plugin-docs/issues/42) in terraform-plugin-docs.

**Comment by shurkus** [comment]
Any news?

**Comment by bbarani** [comment]
@phillbaker can you please take a look when you get a chance?

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
