### PR TITLE
Fix error thrown when index configuration has no number_of_replicas specified

### LINKED ISSUE #83: [BUG] Index resource fails during Apply when configured to ISM rollover policy
### What is the bug?
I've created an initial index test-logs-000001 which has `is_write_index = true` property set and this index is managed by `opensearch_index_template` resource and configured to rollover using ISM policy resource.

But as the rollover occurs, the index test-logs-000002, test-logs-000003...etc, the latest index becomes the write enabled index, and so when I subsequently run terraform plan and apply, it throws the error as below:

`Error: elastic: Error 500 (Internal Server Error): alias [test-logs] has more than one write index [test-logs-000001,test-logs-00010] [type=illegal_state_exception]`
 
### How can one reproduce the bug?

- Create index, index template and ism rollover policy using the below code and wait for the rollover to occur with then the alias pointed to the latest index and property `is_write_index=true`

``resource "opensearch_ism_policy" "rollover_index_policy" {
  policy_id = "Rollover-and-delete-indexes"
  body = jsonencode(
    {
      "policy" : {
        "description" : "Rollover index and delete it after 7 days",
        "default_state" : "hot",
        "states" : [
          {
            "name" : "hot",
            "actions" : [
              {
                "retry" : {
                  "count" : 3,
                  "backoff" : "exponential",
                  "delay" : "1m"
                },
                "rollover" : {
                  "min_size" : "10gb"
                }
              }
            ],
            "transitions" : [
              {
                "state_name" : "delete",
                "conditions" : {
                  "min_index_age" : "7d"
                }
              }
            ]
          },
          {
            "name" : "delete",
            "actions" : [
              {
                "retry" : {
                  "count" : 3,
                  "backoff" : "exponential",
                  "delay" : "1m"
                },
                "delete" : {}
              }
            ],
            "transitions" : []
          }
        ],
        "ism_template" : [
          {
            "index_patterns" : [
              "test-logs-*"
            ],
            "priority" : "100"
          }
        ]
      }
    }
  )
}

resource "opensearch_index_template" "index_template" {
  name = "test-logs"
  body = jsonencode(
    {
      "index_patterns" : [
        "test-logs-*",
      ],
      "template" : "test-logs-*",
      "settings" : {
        "number_of_shards" : 3,
        "number_of_replicas" : 1,
        "plugins" : {
          "index_state_management" : {
            "rollover_alias" : "test-logs"
          }
        }
      }
    }
  )
}

resource "opensearch_index" "index" {
  name = "test-logs-000001"
  aliases = jsonencode(
    {
      "test-logs" = {
        "is_write_index" = true
      }
    }
  )

  depends_on = [opensearch_index_template.index_template]
}``

### What is your host/environment?
`$ uname -a
Linux PBL244 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ terraform version
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/opensearch-project/opensearch v1.0.0

### PR DESCRIPTION
**Pull request by rblcoder**
### Description
Fix error thrown when index configuration has no number_of_replicas specified 

### Issues Resolved
#83 #108

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rblcoder** [comment]
@prudhvigodithi I have tested this PR with default values.

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder so I assume it dint complain with the default values when executing tf apply?

**Comment by prudhvigodithi** [comment]
Also @rblcoder please try to add some unit tests to this change. Thanks

**Comment by rblcoder** [comment]
@prudhvigodithi Yes, it didn't complain with default values on re-apply. Added tests.

**Comment by prudhvigodithi** [comment]
Great, thanks @rblcoder, the PR LGTM.

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
