### PR TITLE
Import terraform-provider-elasticsearch, update for opensearch

### PR DESCRIPTION
**Pull request by phillbaker**
### Description
Imports terraform-provider elasticsearch with updates to resource names for removing elasticsearch naming

### Issues Resolved
* Closes https://github.com/phillbaker/terraform-provider-elasticsearch/issues/299 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jackson-theisen — APPROVED** [review]

**Comment by jackson-theisen** [comment]
Also closes https://github.com/opensearch-project/opensearch-devops/issues/82, which is directly related to the issue already referenced in the description.

**Comment by phillbaker** [comment]
> Do we want to begin work around completely removing anything with elasticsearch in the name?

This is mostly done in this PR. All resources are now named using opensearch. Looks like I missed the examples directory though, I'll remove those from this PR.

**Comment by bbarani** [comment]
> Also closes [opensearch-project/opensearch-devops#82](https://github.com/opensearch-project/opensearch-devops/issues/82), which is directly related to the issue already referenced in the description.
> 
> @phillbaker Do we want to begin work around completely removing anything with `elasticsearch` in the name? My assumption was that your main focus initially is just to get the repo bootstrapped. Then we can focus on refactoring and stripping out some of the elasticsearch-specific stuff. Let me know what you had in mind.

Thanks a lot for your contributions. I will second this. It would be great if we can remove all references to `elasticsearch` in the name before merging this PR.

**Comment by phillbaker** [comment]
@bbarani have you been able to look at the settings on this repo to enable github actions?

**Comment by bbarani** [comment]
> @bbarani have you been able to look at the settings on this repo to enable github actions?

I have enabled GitHub actions now. Please let me know if you are still seeing any issues.

**Pull request merged**
