### PR TITLE
Remove checks for Opensearch version

### LINKED ISSUE #36: [BUG] Error: opensearch version 2.5.0 is older than 6.0.0 and is not supported, flavor: 0.
### What is the bug?
Error: opensearch version 2.5.0 is older than 6.0.0 and is not supported, flavor: 0.

### How can one reproduce the bug?
1.Provisioning AWS Opensearch version 2.5.0.
2.Create some resource with terraform.
**Example**
`resource "opensearch_index_template" "log_aws_default" {
  count = var.environment == "prod" ? 1 : 0
  name = "log-aws_default"
  body = <<EOF
{
  "index_patterns": [ "log-aws-*" ],
  "order": 0,
  "settings": {
    "index": {
      "number_of_shards": "1",
      "number_of_replicas": "1"
    }
  },
  "mappings": {
    "_source": {
      "enabled": true
    }
  },
  "aliases" : {
    "log-aws": {}
  }
}
EOF
}`
3. Run terraform apply.

### What is the expected behavior?
Terraform apply all resources successfully.

### What is your host/environment?
AWS Opensearch version 2.5.0.

### Do you have any screenshots?
`│ Error: opensearch version 2.5.0 is older than 6.0.0 and is not supported, flavor: 0.
│ 
│   with opensearch_ism_policy.log_aws_default[0],
│   on index-opensearch.tf line 2, in resource "opensearch_ism_policy" "log_aws_default":
│    2: resource "opensearch_ism_policy" "log_aws_default" {
│ 
╵
╷
│ Error: opensearch version 2.5.0 is older than 6.0.0 and is not supported, flavor: 0.
│ 
│   with opensearch_index_template.log_aws_default[0],
│   on index-opensearch.tf line 9, in resource "opensearch_index_template" "log_aws_default":
│    9: resource "opensearch_index_template" "log_aws_default" {`

### PR DESCRIPTION
**Pull request by rblcoder**
### Description
Remove checks for Opensearch version

### Issues Resolved
#36 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rblcoder** [comment]
@prudhvigodithi Please review this PR.

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder the PR LGTM, can you please update the the [readme](https://github.com/opensearch-project/terraform-provider-opensearch?tab=readme-ov-file#compatibility) with more details mentioning the support for 2.x series of OpenSearch with the provider 2.x release series? also please add for 1.x version of OpenSerach its recommended to use 1.x version of provider.
Thank you

**Comment by prudhvigodithi** [comment]
Also @rblcoder should we create a seperate readme for versioning  and support, like a matrix any thoughts? Example https://kops.sigs.k8s.io/welcome/releases/ 
https://github.com/prometheus-operator/kube-prometheus?tab=readme-ov-file#compatibility
Adding @bbarani @peterzhuamazon @phillbaker @jackson-theisen

**Comment by rblcoder** [comment]
> Also @rblcoder should we create a seperate readme for versioning and support, like a matrix any thoughts? Example https://kops.sigs.k8s.io/welcome/releases/ https://github.com/prometheus-operator/kube-prometheus?tab=readme-ov-file#compatibility Adding @bbarani @peterzhuamazon @phillbaker @jackson-theisen

@prudhvigodithi I have modified the compatibility information according to the example you have provided.

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
