### PR TITLE
Add import for index mappings

### LINKED ISSUE #135: [BUG] Import of index resource doesn't include mapping configuration
### What is the bug?
When I attempt to import the opensearch_index resource with mapping configured, it doesn't get imported into the state

### How can one reproduce the bug?
Create an index with a mapping configuration:
```
resource opensearch_index "my-index" {
	name               = "my-index"
	mappings           = file("${path.module}/elasticsearch-mappings/my-index.mapping.json")
	number_of_replicas = 1
	number_of_shards   = 5
}
```

Remove it from the state and import it back:
```
terragrunt state rm opensearch_index.my-index
terragrunt import opensearch_index.enriched-contacts my-index
```

The new resource state doesn't have the mapping configuration:
```
terragrunt state show opensearch_index.my-index
# opensearch_index.my-index:
resource "opensearch_index" "my-index" {
    id                 = "my-index"
    name               = "my-index"
    number_of_replicas = "1"
    number_of_shards   = "5"
}
```

### What is the expected behavior?
The mapping is imported.

### What is your host/environment?

Provider:
```
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.26.0"
    }

    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.1.0"
    }
  }
```

Terraform:
```
Terraform v1.5.7
on darwin_arm64
```

### PR DESCRIPTION
**Pull request by rblcoder**
### Description
Implement import of index mappings

### Issues Resolved
#135 #71 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rblcoder** [comment]
Hi @prudhvigodithi  , please review this PR.

**Comment by prudhvigodithi** [comment]
Hey @rblcoder thanks for your contribution, one question I have is since this logic is added to the `resourceOpensearchIndexRead` function is behaviour to 1st read the existing mapping and continue them with next `terraform apply` operations ? When I import the mappings which will be stored in `StateContext` with this code change in `resourceOpensearchIndexRead` does it read the imported mappings and continue with `terraform apply` operation?

Thank you

**Comment by rblcoder** [comment]
@prudhvigodithi The read function is now able to read the mappings attribute from the underlying infrastructure. 
I have tested by removing the resource from state. Then imported it using the import command. The state file is getting updated  successfully with the mappings information. Post this, I am able to run and continue with apply.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder, LGTM.
@bbarani @peterzhuamazon @phillbaker

**Comment by xsnrg** [comment]
@rblcoder Thank you. @prudhvigodithi any chance of getting a new release created with this fix?

**Pull request merged**
