### PR TITLE
Provider compatible with 2.12.0 security plugin admin password change

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Provider compatible with 2.12.0 security plugin admin password change 

### Issues Resolved
part of https://github.com/opensearch-project/security/issues/3624 and https://github.com/opensearch-project/opensearch-build/issues/4115

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Adding @rblcoder @bbarani @peterzhuamazon

**Review by peterzhuamazon — APPROVED** [review]
Why not `myStrongPassword123!`? 😄

**Comment by prudhvigodithi** [comment]
> Why not `myStrongPassword123!`? 😄

Nothing specific @peterzhuamazon  have used `myStrongPassword123@456` as an example in the finalized RC for 2.12.0 release https://github.com/opensearch-project/opensearch-build/issues/4115#issuecomment-1953322664, hence used it.

**Review by rblcoder — APPROVED** [review]
The changes are working in the Github workflow. The tests are also running fine locally with the latest OpenSearch release.

**Pull request merged**
