### PR TITLE
Add anomaly detection

### LINKED ISSUE #84: [FEATURE] Add anomaly detection support
Can we create a terraform resource for Opensearch anomaly detection capabilities?

Thanks,
Tony

### PR DESCRIPTION
**Pull request by rblcoder**
### Description
Add anomaly detection support

### Issues Resolved
#84 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rblcoder** [comment]
@prudhvigodithi I get an error 
Error: elastic: Error [40](https://github.com/opensearch-project/terraform-provider-opensearch/actions/runs/6561579673/job/17821632900?pr=105#step:13:41)0 (Bad Request): Can't create anomaly detector as no document is found in the indices: [security-auditlog*] [type=status_exception]
The test runs successfully locally as I have interacted with opensearch locally.
I am wondering that authenticating itself would have created an event https://opensearch.org/docs/latest/security/audit-logs/index/

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @rblcoder LGTM.

**Comment by YogevLevy93** [comment]
@prudhvigodithi When it will be in a release version?

**Comment by amontalban** [comment]
Having the need to have this in the provider so we can codify some anomaly detections 🙏

**Comment by prudhvigodithi** [comment]
Hey @YogevLevy93 and @amontalban thanks for your patience, we should have a new release soon, waiting on few PR's to get merged and plan for a release. Thanks.

**Pull request merged**
