### PR TITLE
Update AWS SDK to fix the CVE issue with golang.org/x/net-v0.1.0

### PR DESCRIPTION
**Pull request by jmaitrehenry**
### Description
Update AWS SDK to latest version for updating the transient golang.org/x/net-v0.1.0 package.

### Issues Resolved
Close https://github.com/opensearch-project/terraform-provider-opensearch/issues/119

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jmaitrehenry** [comment]
Will not completely fix the project CVE as this PR will add a new vuln, but with a lower score.
I created this issue to discuss about the new CVE added by this PR: https://github.com/opensearch-project/terraform-provider-opensearch/issues/151

**Comment by prudhvigodithi** [comment]
Thanks for the contribution @jmaitrehenry, following are security checks failing can you please check?
Screenshot 2024-02-01 at 8 54 02 AM

**Comment by prudhvigodithi** [comment]
Thanks @jmaitrehenry, LGTM. Since you are aware of this can you please give a stab to change the code to `aws-sdk-go-v2` ?
Thanks 
Adding @bbarani @peterzhuamazon @rblcoder

**Review by prudhvigodithi — APPROVED** [review]

**Comment by jmaitrehenry** [comment]
@prudhvigodithi I will check when I will have some time available to do it!

**Comment by prudhvigodithi** [comment]
Thanks @jmaitrehenry closing this PR as this is taken care as part of the repo go upgrade to 1.22 https://github.com/opensearch-project/terraform-provider-opensearch/pull/187.
@rblcoder @bbarani

**Pull request closed without merging**
