### PR TITLE
Support index alias update on an existing index using `opensearch_index`

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Support index alias update on an existing index using `opensearch_index`.

### Issues Resolved
https://github.com/opensearch-project/terraform-provider-opensearch/issues/85 and part of https://github.com/opensearch-project/terraform-provider-opensearch/issues/190

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Adding @peterzhuamazon @rblcoder @getsaurabh02.

**Comment by anuborah** [comment]
Eagerly waiting for this PR to get merged as this PR seems to fix the non deletion of existing index when aliases is updated or  new alias added to an existing index.
@phillbaker @rblcoder @jackson-theisen @peterzhuamazon

**Comment by prudhvigodithi** [comment]
Sure @anuborah doing some final checks on the PR, once done I will ask the maintainers to review and merge.
Thank you 
@getsaurabh02

**Review by peterzhuamazon — APPROVED** [review]
Thanks @prudhvigodithi !

**Pull request merged**
