### PR TITLE
When the provider assumes a given role, don't use the default profile…

### PR DESCRIPTION
**Pull request by massimob76**
… if the profile is not given, but allow aws-sdk-go to find the credentials using the default credential provider chain (#86)

### Description
When `aws_assume_role_arn` is given but no `aws_profile`, it won't set the profile to default but it will let the aws-sdk-go library to find out the credentials using the default provider chain.
When `aws_assume_role_arn` is given as well as `aws_profile`, it won't change its current behaviour and the aws-sdk-go library will use the given profile.

### Issues Resolved
This will revolve issue #86 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Thanks @massimob76 this looks good, any unit tests can be added?

**Comment by massimob76** [comment]
hi @prudhvigodithi I will try to add some unit tests this week, sorry I have been very busy lately.

**Comment by massimob76** [comment]
Hi @prudhvigodithi, I have added some tests - that required a few changes:
- added a mock server for intercepting the api call rather than the real AWS endpoint. Only during tests we use a mock server endpoint when calling awsSession, otherwise endpoint="" which will lead to aws-sdk-go to call its real endpoint.
- swapped the test_aws_config with the test_aws_credentials since when running it locally if a credentials file exists it will have the priority over the test_aws_config fixture. But using test_aws_credentials instead will remove any interference from the local setup.

**Comment by prudhvigodithi** [comment]
Thanks @massimob76 for your contribution, merging the PR now.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by andrejvanderzee** [comment]
Any ETA on releasing this now that it is merged?

**Comment by estebane-frb** [comment]
Any chance this can be released soon? This has been a big blocker for us to be able to use the provider.

**Comment by justinhauer** [comment]
@prudhvigodithi can you give us any type of time frame when you think this will be released?

**Comment by prudhvigodithi** [comment]
Hey @estebane-frb @justinhauer I have an issue created for this purpose https://github.com/opensearch-project/terraform-provider-opensearch/issues/122, I'm planning to go ahead with the release tomorrow (PST), just waiting on one feature PR to support OpenSearch serverless to go in https://github.com/opensearch-project/terraform-provider-opensearch/pull/92
Adding @vasyaxparfenov @bbarani

**Comment by prudhvigodithi** [comment]
The provider `v2.1.0` has been released, please check.
Provider Download link: https://registry.terraform.io/providers/opensearch-project/opensearch/2.1.0

**Pull request merged**
