### PR TITLE
chore(docs): improve OpenSearch spelling

### PR DESCRIPTION
**Pull request by etolbakov**
### Description
Renaming to address spelling issues with `OpenSearch`

### Issues Resolved
https://github.com/opensearch-project/terraform-provider-opensearch/issues/139

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by etolbakov** [comment]
Hello @dblock  could you please take a look when you have time?

**Comment by prudhvigodithi** [comment]
Hey @etolbakov thanks for your contribution, I will very soon review this PR, thanks.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
LGTM!

**Comment by etolbakov** [comment]
Thank you @prudhvigodithi for a quick turnaround!

**Comment by prudhvigodithi** [comment]
@etolbakov can you please backport this to 1.x branch ?

**Comment by etolbakov** [comment]
Just to confirm by backport you mean applying the same set of changes to the `1.x` branch right?
If that's the case, sure will do that

**Comment by prudhvigodithi** [comment]
Yes you are right, update the same changes for 1.x branch.

**Comment by etolbakov** [comment]
Made the backport in https://github.com/opensearch-project/terraform-provider-opensearch/pull/141

**Pull request merged**
