### PR TITLE
Update go-hclog

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Update go-hclog to v1.5.0

### Issues Resolved
https://github.com/opensearch-project/terraform-provider-opensearch/issues/22

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey @phillbaker can you please review.
`go-hclog v1.2.0` depends on `terraform-plugin-sdk/v2 v2.11.0` which again uses `apparentlymart/go-cidr v1.1.0`
Thank you 
@peterzhuamazon @bbarani

**Comment by prudhvigodithi** [comment]
Hey @phillbaker can you please check this PR?
Thank you

**Comment by prudhvigodithi** [comment]
The rebase for the merged [PR](https://github.com/opensearch-project/terraform-provider-opensearch/pull/31), broke the tests, will update this PR with the broken go package dependency.

**Comment by prudhvigodithi** [comment]
Updated the PR to fix the tests, @phillbaker please take a look when you get a chance.
Thank you

**Comment by prudhvigodithi** [comment]
Just adding @phillbaker once we get this PR in, can we do a non beta release?, since the [docs PR ](https://github.com/opensearch-project/terraform-provider-opensearch/pull/31) is merged should be good to go with a stable release.

**Review by phillbaker — APPROVED** [review]

**Pull request merged**
