### PR TITLE
fix(provider): fix working with opensearch

### PR DESCRIPTION
**Pull request by serge-r**
Signed-off-by: serge-r [zoneofmail@gmail.com](mailto:zoneofmail@gmail.com)

fix(dashboard): change default index to .kibana
fix(index): fix defaults
fix(indextemplate): fix depracated functions, fix tests
fix(ism_policy): fix path to ism_policy

### Description
By https://github.com/opensearch-project/terraform-provider-opensearch/pull/16 - reduce amount of changes

### PRs Related
https://github.com/opensearch-project/terraform-provider-opensearch/pull/16

### Issues Related
https://github.com/opensearch-project/terraform-provider-opensearch/issues/39

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by justinhauer** [comment]
Anyone looking at these merge requests? I would like to add this in for OS 2.x.x myself

**Comment by andrejvanderzee** [comment]
@phillbaker @prudhvigodithi @peterzhuamazon @jackson-theisen Any chance moving this forward to allow 2.x support?

**Comment by prudhvigodithi** [comment]
Hey thanks @serge-r and everyone for the patience, I will look at this PR and will sure give an update by end of this week, meanwhile @serge-r the CI unit tests fail with this PR can you please take a look?
Thank you

**Comment by phillbaker** [comment]
> adding these changes would break the 1.x OpenSearch compatibility (as you can already see the CI tests fail)

Agreed that `main` should target compatibility with 2.x opensearch and we can cut a branch for 1.x updates. We can tag and release updates to 1.x from that branch if necessary. Was the 1.3.x mention for something specific, or was that just an example?

> does this short PR enough for 2.x.x compatibility?

Let's please add tests for 2.x to the test matrix so that we can answer this question using the test suite.

**Comment by phillbaker** [comment]
> fix(dashboard): change default index to .kibana

This actually seems like a bug in 1.x from https://github.com/opensearch-project/terraform-provider-opensearch/pull/17, the internal index name is still `.kibana` and not `.dashboard`.

**Comment by prudhvigodithi** [comment]
PR released to repo branching https://github.com/opensearch-project/terraform-provider-opensearch/pull/43, once merged I will proceed to create a `1.x` branch.
@phillbaker @serge-r @bbarani @peterzhuamazon please check.
Thank you

**Comment by prudhvigodithi** [comment]
> PR related to repo branching #43, once merged I will proceed to create a `1.x` branch. @phillbaker @serge-r @bbarani @peterzhuamazon please check. Thank you

Merged the PR and created a new `1.x` branch https://github.com/opensearch-project/terraform-provider-opensearch/tree/1.x. This PR even though it breaks `1.x` should be fine as merging to `main` should be good with `2.x` releases. WDYT @phillbaker @serge-r ?

**Comment by phillbaker** [comment]
No. Please do not merge this PR - the tests are not passing. Even if it breaks API compatibility, every PR should pass the test suite.

**Comment by prudhvigodithi** [comment]
Closing this PR, please check the latest PR that has all the support for `2.x` https://github.com/opensearch-project/terraform-provider-opensearch/pull/62.
Thank you

**Pull request closed without merging**
