### PR TITLE
Bump github.com/hashicorp/go-getter to 1.6.1

### PR DESCRIPTION
**Pull request by rishabh6788**
Signed-off-by: Rishabh Singh <sngri@amazon.com>

### Description
Bump github.com/hashicorp/go-getter to 1.6.1. 

### Issues Resolved
https://github.com/opensearch-project/terraform-provider-opensearch/security/dependabot/4

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Thanks @rishabh6788, We should test the go run and build with the new version added, I dont see a readme to do that, @phillbaker can you please add your thoughts.
Thank you

**Comment by rishabh6788** [comment]
@prudhvigodithi +1 on the documentation around building, testing and using the repo. 
Also, the test workflow have run successfully, aren't they sufficient to confirm the changes don't break anything?

**Comment by phillbaker** [comment]
If the test workflows on GitHub actions complete successfully, then it
confirms the go build is succeeding. If everything is green, you should be
good to go.

**Comment by prudhvigodithi** [comment]
Hey @phillbaker I can see all the workflows are successful, good to merge?
Thank you

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
